REMOTE_URL:
  - file:///opt/spaceone/identity/config/database.yaml
  - file:///opt/spaceone/identity/config/shared.yaml
  - file:///opt/spaceone/identity/config/application.yaml
GLOBAL:
  MAX_WORKERS: 1000
  DATABASES:
    default:
      db: identity
      host: mongodb
      port: 27017
      maxPoolSize: 200
      username: identity_user
      password: identity_password
  CACHES:
    default:
      backend: spaceone.core.cache.redis_cache.RedisCache
      host: redis
      port: 6379
      encoding: utf-8
      socket_timeout: 10
      socket_connect_timeout: 10
  LOG:
    loggers:
      spaceone:
        handlers:
          - console
          - file
    handlers:
      file:
        type: file
        filename: /var/log/spaceone/identity.log
